### ISSUE TITLE
Missing Gas usage

### ISSUE THREAD

**Issue by nachtbraker** [RaimondB/node-red-contrib-nefit-easy#158]
**Is your feature request related to a problem? Please describe.**
There exists the possibility to retrieve the Gas Usage. It would be great if this was also available in this Nefit node.

**Describe the solution you'd like**
Add this data from the client library.

**Comment by RaimondB** [comment]
This is indeed something that could be done. But the standard library will give a paged result. What do you want to achieve; so that we can think of a good solution?

**Comment by nachtbraker** [comment]
Forgive me for my late reply. I somehow missed your comment.

I basically dump everything into influxdb and go from there. So I have no need for paged data. Is daily the most fine-grained data that can be requested?

**Comment by RaimondB** [comment]
> I basically dump everything into influxdb and go from there. So I have no need for paged data. Is daily the most fine-grained data that can be requested?

I have done some local tests. The good news is that the command is fairly easy to integrate, so I could make it available.
The bad news is that the output might not be what you are expecting.

It will by default report on the stats of the current month. But it apparently can also be a few days behind. This is the output I have run today

```
[
  {
    date: 2020-08-01T22:00:00.000Z,
    'hot water': 12.9,
    'central heating': 0,
    'average outdoor temperature': 19.3
  },
  {
    date: 2020-08-02T22:00:00.000Z,
    'hot water': 9.6,
    'central heating': 0,
    'average outdoor temperature': 17.2
  },
  {
    date: 2020-08-03T22:00:00.000Z,
    'hot water': 9.2,
    'central heating': 0,
    'average outdoor temperature': 18.1
  },
  {
    date: 2020-08-04T22:00:00.000Z,
    'hot water': 16.9,
    'central heating': 0,
    'average outdoor temperature': 21.9
  },
  {
    date: 2020-08-05T22:00:00.000Z,
    'hot water': 14.3,
    'central heating': 0,
    'average outdoor temperature': 24.6
  },
  {
    date: 2020-08-06T22:00:00.000Z,
    'hot water': 8.4,
    'central heating': 0,
    'average outdoor temperature': 27.2
  },
  {
    date: 2020-08-07T22:00:00.000Z,
    'hot water': 10.4,
    'central heating': 0,
    'average outdoor temperature': 28
  },
  {
    date: 2020-08-08T22:00:00.000Z,
    'hot water': 11.1,
    'central heating': 0,
    'average outdoor temperature': 28.5
  },
  {
    date: 2020-08-09T22:00:00.000Z,
    'hot water': 15.6,
    'central heating': 0,
    'average outdoor temperature': 27.6
  }
]
```

As you can see the stats appear to be two days old. Also I currently have no idea if it is updated daily or with a different frequency, which might make it harder to process to send to influx, because you would need some way to determine which values were already sent to prevent duplicate values from getting inserted. But maybe influx itself can also do something smart there?

**Comment by nachtbraker** [comment]
Interesting! Not sure if influxdb can do anything (I'm not very fluent in it). But it would also be possible to do some rbe-style filtering in node-red of course.

**Comment by RaimondB** [comment]
I have now a working setup, including the translation of the data with a node red flow to publish to influx (I am also using it myself).
I will add those examples to the repository.

This flow is the typical setup to get data from the nefit easy to influx. It will get the latest page of data and translate to the influx layout. Because the data contains a timestamp, this will be automatically overwritten and thereby having the effect of not creating duplicate entries :-)

![image](https://user-images.githubusercontent.com/12556944/90039004-5ff8d600-dcc6-11ea-9d89-73778b04c21b.png)

To help get all history from the nefit into influx, I have created this flow that will:
- Get the latest page number
- Loop from 1 to latest page each time triggering the import of a page
- Waiting between actions to prevent running into "MAX_RETRIES" when we query too often.

![image](https://user-images.githubusercontent.com/12556944/90038780-18724a00-dcc6-11ea-8009-864a09a9719e.png)

This enabled me to create this panel in Grafana which I have running on top on influxdb.
![image](https://user-images.githubusercontent.com/12556944/90039586-24aad700-dcc7-11ea-9c41-87b998092a12.png)

**Comment by RaimondB** [comment]
If you install the beta version manually  you can test it out.
`npm install node-red-contrib-nefit-easy2@2.0.0-beta.1`

The examples you can find here: https://github.com/RaimondB/node-red-contrib-nefit-easy/tree/update-deps/examples

**Comment by nachtbraker** [comment]
@RaimondB Thank you very much, works very well!

I was also able to use both example flows. I imported the whole history back to the end of 2016 when I installed the Easy. Very nice!

The only question I have is about the units. I see you use kWh in Grafana. In my iOS Nefit app, it shows boiler gas usage in m3. Are you sure about the units?

Ben

**Comment by nachtbraker** [comment]
@RaimondB One more question: I noticed that the data seems to be missing the last day. At the moment the last entry in influxdb is from 2020-08-16T22:00:00Z, while the current time is 2020-08-18T12:17:00Z. So I'd expect an additional entry for 2020-08-17. Same thing happened yesterday, but I wanted to wait another day to see if it persisted.

Could this be an issue on the Nefit side, or the library?

Thanks,
Ben

**Comment by RaimondB** [comment]
> @RaimondB One more question: I noticed that the data seems to be missing the last day. At the moment the last entry in influxdb is from 2020-08-16T22:00:00Z, while the current time is 2020-08-18T12:17:00Z. So I'd expect an additional entry for 2020-08-17. Same thing happened yesterday, but I wanted to wait another day to see if it persisted.
> 
> Could this be an issue on the Nefit side, or the library?
> 
> Thanks,
> Ben

This is because the reported time is in UTC format by the Nefit. So 2020-08-16T22:00:00Z actually means exactly the same as 2020-08-17 00:00 local time in NL. So it is in fact correct. And indeed it will only report on full days, so the most up-to-date report is always including the number of yesterday. The flow I created runs once a day, and will make sure that already existing values in influx are overwritten.

**Comment by RaimondB** [comment]
Btw, in the mean time the feature has been integrated in the official 2.0.0 release, so you are able to update it via the pallette.

**Comment by nachtbraker** [comment]
Clear, thank you for the clarification. It's been working perfectly for the last few days now, and I already upgraded through the pallette.

Any comments on the units (kWh or m3)? I'm beginning to suspect that the iOS app just has a conversion because you can change the units (m3 or €) and kind of gas (natural / LPG).

Ben

**Comment by RaimondB** [comment]
> Any comments on the units (kWh or m3)? I'm beginning to suspect that the iOS app just does a conversion internally because you can change the units (m3 or €) and kind of gas (natural / LPG).
> 
> Ben

Indeed the units are kwh. You need to use a conversion factor to go to M3.

See here for information on the factors to use. This can easily be integrated in the mapping function of the flow. https://github.com/robertklep/nefit-easy-core/wiki/List-of-endpoints

**Comment by nachtbraker** [comment]
Ok, that clears it up indeed. Thanks again!
